--liquibase formatted sql
--changeset Gleb:1
create table socks
(
    id           int8 generated by default as identity,
    color        varchar(255),
    cotton_part   int8 check ( socks.cotton_part>=0 ) check ( socks.cotton_part<=100 ),
    primary key (id)
);

create table stock
(
    id       int8 generated by default as identity,
    socks_id int8 references socks,
    quantity int8 check ( stock.quantity>0 ),
    primary key (id)
);